[package]
name = "jackfield"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.8", features = ["v4"] }
bitflags = {version = "2.4"}
tokio = { version = "1", features = ["sync", "rt", "macros", "time"] }
tonic = { version = "0.12", features = ["transport"] }
prost = "0.13"
tokio-stream = "0.1"
tokio-tungstenite = "0.24"
futures-util = "0.3"

pyo3 = { version = "0.23", features = ["extension-module", "abi3-py38"], optional = true }

[build-dependencies]
tonic-build = "0.12"

[features]
python = ["dep:pyo3"]
# ---
default = []

[lib]
crate-type = ["cdylib", "rlib"]
